name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install git golang liblzma-dev

      - uses: actions/checkout@v7

      - name: Build
        run: go build .

      - name: Build amd64 v3
        run: GOAMD64=v3 go build -o payload-dumper-go.v3 .

      - name: Test
        run: go test ./...
